### ISSUE TITLE
Using with Propertys?

### ISSUE THREAD

**Issue by visign3d** [peterdongan/UndoService#2]
Hi,
Is it a way , to use with property getter/setters methods ?

**Comment by peterdongan** [comment]
Hi, sorry, I only just saw this today. I haven't been getting notifications.

I'm going to update the examples in the documentation, which might answer your question. I will ping this issue when I have done so.

**Comment by visign3d** [comment]
Hi , it would be great. Also is there a way to record multiple property changes in one record? (batch recording)

**Comment by peterdongan** [comment]
No worries.

RecordState() captures the entire state of the tracked object, including all property changes since the last time the state was recorded.

**Comment by peterdongan** [comment]
I've updated the documentation here and added a corresponding example in the Test project.

Hope this answers your question. If not, please give more details of what you looking to do.

**Comment by visign3d** [comment]
I meant using with property:

`public int statefullInt {get{…}set{…}}`

**Comment by peterdongan** [comment]
You can't use the property accessors directly, but you can use them in the GetState and SetState delegates.

Here is an example of how to set all the properties for an object by serializing it. (You would most likely use a binary serializer in practice.)

https://github.com/peterdongan/UndoService/blob/master/UndoService/UndoService.Test/UndoServiceWIthMutableObjectsExample.cs

An example of how to set a particular selection of properties is in UndoRedoTests:

```
            var trackedObject = new StatefulClass { TheString = "One", TheInt = 1 };
            var undoService = new UndoService<StatefulClassDto>(trackedObject.GetData, trackedObject.SetData, null);
```

 ```
   class StatefulClass
    {
        public int TheInt { get; set; }
        public string TheString { get; set; }

        public void GetData(out StatefulClassDto dto)
        {
            dto = new StatefulClassDto { TheInt = TheInt, TheString = TheString };
        }

        public void SetData(StatefulClassDto dto)
        {
            TheInt = dto.TheInt;
            TheString = dto.TheString;
        }
    }
```
