### ISSUE TITLE
Incorrect value retrieved from Undo action

### ISSUE THREAD

**Issue by jorgomezga** [peterdongan/UndoService#3]
After applying an undo action, the retrieved state is incorrect. 
This only happens when the stack has been filled, and undo actions are taken until getting back to the original state. 
Then, if the stack is filled again, and undo action are applied afterwards, the latest undo action retrieves a value that is not correct.

I'm attaching the code of a very simple console application showing the issue. Hope it can serve to illustrate the problem.

``` 
using StateManagement;

namespace ConsoleApp1
{
class Program
    {
        private static void GetState(out Person state)
        {
            state = (Person)_person.Clone();
        }

        private static void SetState(Person value)
        {
            _person = value;
        }

        private static Person _person;

        static void Main(string[] args)
        {
            // _person.Id set to zero in the constructor
            _person = new Person(); 

            // Original element -> Id set to zero
            var undoService =
                new UndoService<Person>(GetState, SetState, null);
            
            // First element in the stack
            _person.Id = "One";
            undoService.RecordState();
            // Second element in the stack
            _person.Id = "Two";
            undoService.RecordState();

            // Undo -> Back to first element in stack
            undoService.Undo();
            var resA = _person.Id.Equals("One");
            // Undo -> Back to original element in stack
            undoService.Undo();
            var resB = _person.Id.Equals("Zero");

            // NOTE: When this is used, the code seems to work (it does not if using ClearUndoStack)
            // At this point it looks like the original state is replaced by another one
            //_undoServiceForIInformacionPersonal.Reset();

            // First element in stack -> Id = "Three"
            _person.Id = "Three"; 
            undoService.RecordState();
            // Second element in stack -> Id = "Four"
            _person.Id = "Four";
            undoService.RecordState();
            
            // Undo -> Back to first element in stack
            undoService.Undo();
            var resC = _person.Id.Equals("Three");
            // Undo -> Back to original element in stack
            undoService.Undo();
            // Should be "Zero", but it is "Four"
            var resD = _person.Id.Equals("Zero");
        }
    }

    public class Person
    {
        public string Id { get; set; }

        // Constructor
        public Person()
        {
            Id = "Zero";
        }

        // Deep clone
        public object Clone()
        {
            return MemberwiseClone();
        }
    }
}
```
Am I using the library in an incorrect manner? Thanks in advance for any feedback! And thanks for the amazing work with the library!

**Comment by peterdongan** [comment]
Hi @jorgomezga 

Thank you for your feedback and kind words. Sorry for the late reply. I only saw this today. I need to look at how to set up notifications for issues here.

In your example, if you replace your SetState() method with the following, it will work as expected:

```
        private void SetState(Person value)
        {
            _person = (Person)value.Clone();
        }
```
Otherwise, when you use undo or redo, the state will be the same object that is on the stack, and any changes to it will be applied to the object on the stack as well, which is what caused the anomalous behaviour here.

Thank you for drawing my attention to this way of using the library. I see that I need to update the documentation, in particular the examples provided.

**Comment by peterdongan** [comment]
I've updated the documentation to explain this, so I will close this issue.

**Comment by jorgomezga** [comment]
Thanks, it works as expected with the changes you suggested. Also, thanks for updating the documentation; it helps to clarify the use of this handy library!

Keep up the good work!
